name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyaudio numpy pywin32 pyinstaller

      - name: Compile to EXE (正确的 PowerShell 换行格式)
        run: |
          pyinstaller --onefile --windowed `
                      --name "Silence_Grows_Trees" `
                      --add-data "fonts;fonts" `
                      main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: silence-garden-exe
          path: dist/Silence_Grows_Trees.exe