name: Build Windows EXE

on:
  push:
    branches: [ "main" ]  # 推送 main 分支时触发工作流
  release:
    types: [ created ]    # 发布新版本时触发（可选）

jobs:
  build:
    name: Compile to EXE
    runs-on: windows-latest  # 使用最新的 Windows 运行环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取仓库代码

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 选择兼容 PyQt5 和 pyaudio 的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyaudio numpy pywin32 pyinstaller  # 安装项目依赖
          pip install --no-deps pyaudio  # 确保 pyaudio 二进制依赖正确安装（可选优化）

      - name: Compile with PyInstaller
        run: |
          pyinstaller --onefile --windowed ^  # 生成单个文件，无控制台窗口
                      --name "Silence_Grows_Trees" ^  # 生成的 EXE 文件名
                      --add-data "fonts;fonts" ^  # 包含字体文件夹（Windows 格式：源路径;目标路径）
                      --icon=NONE ^  # 若有图标文件，替换为 --icon=icon.ico
                      main.py  # 入口文件

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Silence_Grows_Trees  # 构建产物名称
          path: dist/Silence_Grows_Trees.exe  # 生成的 EXE 路径